[package]
name = "xalliance-netcode"
version = "0.1.0"
edition = "2021"
authors = ["gorynich_"]

[dependencies]
tarpc = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
futures = { workspace = true }
tokio = { workspace = true }
